name: Release

on: 
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        type: choice
        options:
        - patch
        - minor
        - major


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Build and publish
        run: |
          poetry version ${{ inputs.release_type }}
          poetry build
          poetry publish --no-interaction

      - name: Generate release tag
        run: echo "RELEASE_TAG=v$(poetry version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Commit release tag
        run: |
          git config --global user.name 'Julius Marminge'
          git config --global user.email 'juliusmarminge@users.noreply.github.com'
          git add .
          git commit -m "Release ${{ env.RELEASE_TAG }}"
          git push

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          title: Release ${{ env.RELEASE_TAG }}
